config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events
  resources :users, only: :show

  delete 'leave_event/', to: 'attendances#leave_event'
  post 'attend_event/', to: 'attendances#attend_event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances, source: :attendee

  scope :past, -> { where('date < ?', Time.now) }
  scope :future, -> { where('date > ?', Time.now) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :attendances, foreign_key: :attendee_id
  has_many :attended_events, through: :attendances, source: :attended_event
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def attend_event
    @event = Event.find(params[:event_id])
    @attendance = Attendance.new(attended_event: @event, attendee: current_user)

    if @attendance.save
      redirect_to event_path(@event), notice: "Successfully attended the event."
    else
      flash.now[:alert] = "Failed to attend the event."
      render "events/show"
    end
  end

  def leave_event
    @attendance = Attendance.find(params[:attendance_id])
    @attendance.destroy

    redirect_to event_path(@attendance.attended_event), notice: "Event attendance was successfully destroyed."
  end

  private

  def set_attendance
    @attendance = Attendance.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_event, only: [:show, :destroy]
  before_action :authorize_user, only: [:destroy]

  def index
    @events = Event.all
    @past_events = Event.past
    @future_events = Event.future
  end

  def new
    @event = current_user.events.build
  end

  def set_event
    @event = Event.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to events_path, alert: 'Event not found.'
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end
  
  def show
    @event = Event.find(params[:id])
    @attendance = Attendance.new 
    @past_events = Event.past
    @future_events = Event.future
  end

  
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_path, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :location, :user_id)
  end

  def authorize_user
    redirect_to events_path, alert: "You don't have permission to perform this action." unless current_user == @event.creator
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @attendances = @user.attendances
    @events = @user.events
    @attended_events = Event.where(id: @attendances.pluck(:attended_event_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% if @future_events.any? %>
  <h1 class="centered-header">Future Events</h1>
  <ul class="list-group">
    <% @future_events.each do |event| %>
          <li class="list-group-item mb-2 border">
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <strong style="font-size: 20px;"><%= event.name %></strong>
              </div>
              <div class="btn-group" role="group">
                <% if current_user && current_user == event.creator %>
                  <%= form_with(model: event, method: :delete) do |form| %>
                    <%= form.submit 'Cancel your event', class: 'btn btn-danger' %>
                  <% end %>
                <% end %>
                <%= form_with(model: event, method: :get) do |form| %>
                  <%= form.submit 'See details', class: 'btn btn-primary' %>
                <% end %>
              </div>
            </div>
    <% end %>
  </ul>
<% end %>


<% if @past_events.any? %>
  <h1 class="centered-header">Past Events</h1>
  <ul class="list-group">
    <% @past_events.each do |event| %>
        <li class="list-group-item mb-2 border">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <strong style="font-size: 20px;"><%= event.name %></strong>
            </div>
            <div class="btn-group" role="group">
              <% if current_user && current_user == event.creator && @future_events.include?(event)%>
                <%= form_with(model: event, method: :delete) do |form| %>
                  <%= form.submit 'Delete', class: 'btn btn-danger' %>
                <% end %>
              <% end %>
              <%= form_with(model: event, method: :get) do |form| %>
                <%= form.submit 'See details', class: 'btn btn-primary' %>
              <% end %>
            </div>
          </div>
    <% end %>
  </ul>
<% end %>

app/views/events/new.html.erb
<h2>Create a New Event</h2>

<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Event' %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center">
      <h2 class="centered-header"><%= @event.name %></h2>
    </div>
    <div class="col-md-6">
      <p><strong>Description:</strong> <%= @event.description %></p>
      <p><strong>Date:</strong> <%= @event.date %></p>
      <p><strong>Location:</strong> <%= @event.location %></p>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-6 offset-md-3 text-center">
      <div class="d-flex justify-content-center align-items-center button-container">
        <% if current_user == @event.creator && @future_events.include?(@event)%>
          <%= form_with(model: @event, method: :delete) do |form| %>
            <%= form.submit 'Cancel your event', class: 'btn btn-danger' %>
          <% end %>
        <% elsif current_user && current_user.attendances.exists?(attended_event_id: @event.id) && @future_events.any? && @future_events.include?(@event) %>
          <%= form_with(url: leave_event_path(attendance_id: current_user.attendances.find_by(attended_event_id: @event.id)), method: :delete) do |form| %>
            <%= form.submit 'Leave Event', class: 'btn btn-danger' %>
          <% end %>
        <% elsif @future_events.include?(@event) %>
          <%= form_with(url: attend_event_path(event_id: @event), method: :post) do |form| %>
            <%= form.submit 'Attend Event', class: 'btn btn-success' %>
          <% end %>
        <% end %>
        <%= link_to 'Back to Events', events_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <p><strong>List of attendees:</strong> 
      <ul>
        <% @event.attendances.each do |attendance| %>
          <li><%= User.find(attendance.attendee_id).email %></li>
        <% end %>
      </ul>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-center py-3">
  <div class="container">
    <div class="row">
      <div class="col-12 d-flex justify-content-between">
        <p class="text-white mb-0">
          &copy; 2023 <a href="https://www.theodinproject.com/" target="_blank" rel="noopener noreferrer" class="text-white">The Odin Project</a>. All rights reserved.
        </p>
        <p class="text-white mb-0">
          Made by <a href="https://github.com/ckec" target="_blank" rel="noopener noreferrer" class="text-white">ckec</a>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Private Events</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if current_user %>
          <li class="nav-item"> <%= link_to "My Events", user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"> <%= link_to "Create Event", new_event_path, class: "nav-link" %></li>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <li class="nav-item"> <%= link_to "Edit User", edit_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-small btn-primary mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %></li>
          <li class="nav-item"> <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "styles", media: "all" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning alert-dismissible fade show mb-0" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="container-fluid">
      <%= yield %>
    </div>
     <%= render 'layouts/footer' %> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous" type = "module"></script>
  </body>
</html>

app/views/users/show.html.erb
<div class="text-center m-4">
  <h1>User Profile</h1>
</div>

<div class="container flex align-items-center">
  <div class="row">

    <!-- Left Column -->
    <div class="flex">
      <div class="text-center pb-5">
        <h4>Events created by you</h4>
      </div>

      <% if @events.any? %>
        <% @events.each do |event| %>
          <ul>
            <li>
              <h5><strong><%= event.name %></strong></h5>
              <p>Date: <%= event.date %></p>
              <p><%= link_to 'See details', event_path(event), class: 'btn btn-primary' %></p>
            </li>
          </ul>
        <% end %>
      <% else %>
        <div class="text-danger text-center">
          <p>You haven't created any events.</p>
        </div>
      <% end %>
    </div>

    <hr class="my-4">

    <!-- Right Column -->
    <div class="flex">
      <div class="text-center pb-5">
        <h4>Future events you attend</h4>
      </div>

      <% if @attended_events.any? { |attended_event| attended_event.date > Time.now } %>
        <% @attended_events.each do |attended_event| %>
          <% if attended_event.date > Time.now %>
            <ul>
              <li>
                <h5><strong><%= attended_event.name %></strong></h5>
                <p>Date: <%= attended_event.date %></p>
                <p><%= link_to 'See details', event_path(attended_event), class: 'btn btn-primary' %></p>
              </li>
            </ul>
          <% end %>
        <% end %>
      <% else %>
        <div class="text-danger text-center">
          <p>You aren't attending any future events.</p>
        </div>
      <% end %>

      <hr class="my-4">

      <div class="text-center pb-5">
        <h4>Past events you attended to</h4>
      </div>

      <% if @attended_events.any? { |attended_event| attended_event.date < Time.now } %>
        <% @attended_events.each do |attended_event| %>
          <% if attended_event.date < Time.now %>
            <ul>
              <li>
                <h5><strong><%= attended_event.name %></strong></h5>
                <p>Date: <%= attended_event.date %></p>
                <p><%= link_to 'See details', event_path(attended_event), class: 'btn btn-primary' %></p>
              </li>
            </ul>
          <% end %>
        <% end %>
      <% else %>
        <div class="text-danger text-center">
          <p>You haven't attended to any event in the past.</p>
        </div>
      <% end %>
    </div>
  </div>
</div>